[project]
name = "uv-tool"
version = "0.0.1"
description = "Some useful bash command for uv and for managing virtual environments."
authors = [{ name = "Simone Martino" }]
requires-python = ">=3.8"

[project.scripts]
uv-tool = "uv_tool.main:main"
